version: '3'

services:
    api:
        build: 
            context: ./api
            target: ${API_TARGET}
        env_file: 
            - api/.env
        command: python3 manage.py runserver 0.0.0.0:${API_PORT}
        volumes:
        - ./api:/app
        ports:
        - ${API_PORT}:${API_PORT}
    frontend:
        build: 
            context: ./frontend
            target: ${FRONTEND_TARGET}
        env_file: 
            - frontend/.env
        command: npm run dev -- -p ${FRONTEND_PORT}
        volumes:
        - ./frontend/src:/app/src
        ports:
        - ${FRONTEND_PORT}:${FRONTEND_PORT}
        depends_on:
            - api
    nginx:
        build: 
            context: ./nginx
            target: ${NGINX_TARGET}
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
        env_file: 
            - nginx/.env
        depends_on:
            - api
            - frontend
