version: '3'

services:
    api:
        build: 
            context: ./api
            target: ${API_TARGET}
            args: 
                - PORT=${API_PORT}
                - SECRET_KEY=${API_SECRET_KEY}
        env_file: 
            - api/env/local.env
        volumes:
            - ./api:/app
            - static_volume:/app/staticfiles
        ports:
            - ${API_PORT}:${API_PORT}
    frontend:
        build: 
            context: ./frontend
            target: ${FRONTEND_TARGET}
            args: 
                - PORT=${FRONTEND_PORT}
        env_file: 
            - frontend/env/local.env
        volumes:
            - ./frontend/src:/app/src
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        depends_on:
            - api
    nginx:
        build: 
            context: ./nginx
            target: ${NGINX_TARGET}
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
        env_file: 
            - nginx/env/local.env
        volumes:
            - static_volume:/var/www/api/staticfiles/
        depends_on:
            - api
            - frontend

volumes:
    static_volume:
    letsencrypt:
