version: '3'

services:
    api:
        build: 
            context: ./api
            target: ${API_TARGET}
            args: 
                SECRET_KEY: ${API_SECRET_KEY}
                DATABASE_URL: ${API_DATABASE_URL}
        env_file: 
            - api/env/production.env
        volumes:
            - ./api:/app
            - static_volume:/app/staticfiles
        expose:
            - ${API_PORT}
    frontend:
        build: 
            context: ./frontend
            target: ${FRONTEND_TARGET}
            args: 
                PORT: ${FRONTEND_PORT}
        env_file: 
            - frontend/env/production.env
        volumes:
            - ./frontend/src:/app/src
        expose:
            - ${API_PORT}
        depends_on:
            - api
    nginx:
        build: 
            context: ./nginx
            target: ${NGINX_TARGET}
        ports:
            - 80:80
            - 443:443
        env_file: 
            - nginx/env/production.env
        volumes:
            - static_volume:/var/www/api/staticfiles/
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        depends_on:
            - api
            - frontend

volumes:
    static_volume:
