# Generated by Django 3.2.9 on 2021-12-15 10:37

import autoslug.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
from django.utils.text import slugify


def gen_slug(apps, schema_editor) -> None:
    Workout = apps.get_model('workouts', 'Workout')
    for row in Workout.objects.all():
        row.slug = slugify(row.name)
        row.save(update_fields=['slug'])

    Exercise = apps.get_model('workouts', 'Exercise')
    for row in Exercise.objects.all():
        row.slug = slugify(row.name)
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workoutactivity',
            options={'verbose_name': 'workout activity', 'verbose_name_plural': 'workout activities'},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'verbose_name': 'workout plan', 'verbose_name_plural': 'workout plans'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
        migrations.AddField(
            model_name='workout',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
