# Generated by Django 3.2.9 on 2021-12-15 13:30

import autoslug.fields
from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_auto_20211215_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('user', 'slug')},
        ),
    ]
