# Generated by Django 3.2.9 on 2021-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20211215_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
