# Generated by Django 3.2.9 on 2021-12-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexerciseset',
            name='reps',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutexerciseset',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
