#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Frontend linting
echo "Checking js formatting"
(cd frontend && npm run lint)

# Backend linting
echo "Checking python formatting"
(cd api && black . && isort . && autoflake .)
