name: Deploy on digital ocean

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test api
        run: cp env/testing.env .env && cp api/env/testing.env api/.env && cp frontend/env/testing.env frontend/.env && cp nginx/env/testing.env nginx/.env && docker-compose up --build api

  deploy:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd MyWorkout && git pull \
            && cp env/production.env .env \
            && export API_DATABASE_URL='${{secrets.API_DATABASE_URL}}' API_SECRET_KEY='${{secrets.SECRET_KEY}}' \
            && docker-compose -f docker-compose.production.yml up -d --no-deps --build \
            && echo "Deployed successfully to Digital Ocean"
